import { Bot, Sparkles } from "lucide-react";
import { motion } from "framer-motion";

const AiBanner = () => {
  return (
    <motion.div
      initial={{ y: -60 }}
      animate={{ y: 0 }}
      transition={{ type: "spring", stiffness: 200, damping: 20 }}
      className="fixed top-0 left-0 right-0 z-50 bg-primary text-primary-foreground"
    >
      <div className="max-w-7xl mx-auto px-4 py-2.5 flex items-center justify-center gap-3 text-sm font-medium">
        <Bot className="w-5 h-5 animate-bounce" />
        <span>
          🤖 This entire website was generated by AI using{" "}
          <a
            href="https://lovable.dev"
            target="_blank"
            rel="noopener noreferrer"
            className="underline underline-offset-2 font-bold"
          >
            Lovable
          </a>
          {" "}— no humans were harmed in the making of this page
        </span>
        <Sparkles className="w-5 h-5" />
      </div>
    </motion.div>
  );
};

export default AiBanner;
